spring:
  application:
    name: 'movieflix'
  datasource:
    url: jdbc:mysql://localhost:3306/movieflix
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 600000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  flyway:
    enabled: true
